MODEL:
  META_ARCHITECTURE: "AttrRCNN"
  WEIGHT: "pretrained/vinvl_vg_x152c4.pth"
  BACKBONE:
    CONV_BODY: "R-152-C4"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 300
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 384 # 512
    POSITIVE_FRACTION: 0.5 # 0.25
    SCORE_THRESH: 0.1 # 0.0001
    DETECTIONS_PER_IMG: 36 # 600
    MIN_DETECTIONS_PER_IMG: 1
  ROI_BOX_HEAD:
    NUM_CLASSES: 117
  ATTRIBUTE_ON: False
  RELATION_ON: False
INPUT:
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1200
  PIXEL_MEAN: [103.530, 116.280, 123.675]
DATASETS:
  #   FACTORY_TEST: ("ODTSVDataset",)
  #   TEST: ("flickr30k/tsv/flickr30k.yaml",)
  TRAIN: ("train/train.yaml",)
  TEST: ("valid_seen/train.yaml",)
  FACTORY_TRAIN: ("VGTSVDataset",)
  FACTORY_TEST: ("VGTSVDataset",)
DATALOADER:
  NUM_WORKERS: 0
SOLVER:
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.00001
  MAX_ITER: 36000
  STEPS: (15000, 25000)
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 5000
  TEST_PERIOD: 4000
TEST:
  IMS_PER_BATCH: 16
  SKIP_PERFORMANCE_EVAL: False
  SAVE_PREDICTIONS: True
  SAVE_RESULTS_TO_TSV: True
  TSV_SAVE_SUBSET: ["rect", "class", "conf", "feature"]
  GATHER_ON_CPU: False
  OUTPUT_FEATURE: True
OUTPUT_DIR: "./output/X152C4_test_weight_e2"
DATA_DIR: "datasets/alfred/"
DISTRIBUTED_BACKEND: "gloo"
